sealtalk-config:
  config_env: dev
  auth_cookie_name: test_cookie_name
  auth_cookie_key: abcd123
  auth_cookie_max_age: 8640000
  auth_cookie_domain: test.net
  rongcloud_app_key: APP_KEY
  rongcloud_app_secret: APP_SECRET
  rongcloud_api_url: URL1,URL2,URL3...
  ai_api_url: AI_API_URL
  rongcloud_default_portrait_url: IMAGE_URL
  qiniu_access_key: QINIU_ACCESS_KEY
  qiniu_secret_key: QINIU_SECRET_KEY
  qiniu_bucket_name: QINIU_BUCKET_NAME
  qiniu_bucket_domain: QINIU_BUCKET_DOMAIN
  ali_sms_access_key_id: ALI_SMS_ACCESS_KEY_ID
  ali_sms_access_key_secret: ALI_SMS_ACCESS_KEY_SECRET
  sms_limited_time: 1
  sms_limited_count: 100
  shumei_access_key: SHUMEI_ACCESS_KEY
  shumei_app_id: SHUMEI_APP_ID
  shumei_api_url: SHUMEI_API_URL
  n3d_key: 1a2b3c4d5e
  cors_hosts:  '*'
  server_port: SERVER_PORT
  db_name: DB_NAME
  db_user: DB_USER
  db_password: DB_PASSWORD
  db_host: DB_HOST
  db_port: DB_PORT
  ai_agent_model: AI_AGENT_MODEL
  admin_auth_key: ADMIN_AUTH_KEY